/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelUmbralizacion.java
 *
 * Created on 10/04/2012, 05:00:35 PM
 */
package gui;

/**
 *
 * @author juansrs
 */
public class PanelUmbralizacion extends javax.swing.JPanel {

    /** Creates new form PanelUmbralizacion */
    public PanelUmbralizacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelValorIsodata = new javax.swing.JLabel();
        labelValorOtsu = new javax.swing.JLabel();
        btnCalcularOtsu = new javax.swing.JButton();
        btnCalcularIsodata = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCalcularDosPicos = new javax.swing.JButton();
        labelValorDosPicos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textFieldValorUmbral = new javax.swing.JTextField();
        btnCalcularImgBinaria = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Umbralizacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setMinimumSize(new java.awt.Dimension(299, 304));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Metodo Otsu:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Metodo Isodata:");

        labelValorIsodata.setText("valor");

        labelValorOtsu.setText("valor");

        btnCalcularOtsu.setText("Calcular");

        btnCalcularIsodata.setText("Calcular");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Metodo Dos Picos:");

        btnCalcularDosPicos.setText("Calcular");

        labelValorDosPicos.setText("valor");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen Binaria", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Valor Umbral:");

        btnCalcularImgBinaria.setText("Calcular");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldValorUmbral, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(btnCalcularImgBinaria, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldValorUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularImgBinaria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularOtsu)
                                .addGap(18, 18, 18)
                                .addComponent(labelValorOtsu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularIsodata)
                                .addGap(18, 18, 18)
                                .addComponent(labelValorIsodata))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularDosPicos)
                                .addGap(18, 18, 18)
                                .addComponent(labelValorDosPicos)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCalcularOtsu)
                    .addComponent(labelValorOtsu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCalcularIsodata)
                    .addComponent(labelValorIsodata))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnCalcularDosPicos)
                    .addComponent(labelValorDosPicos))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcularDosPicos;
    public javax.swing.JButton btnCalcularImgBinaria;
    public javax.swing.JButton btnCalcularIsodata;
    public javax.swing.JButton btnCalcularOtsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelValorDosPicos;
    public javax.swing.JLabel labelValorIsodata;
    public javax.swing.JLabel labelValorOtsu;
    public javax.swing.JTextField textFieldValorUmbral;
    // End of variables declaration//GEN-END:variables
}
