/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.controlador.ControladorSegmentacion;

/**
 *
 * @author sebaxtian
 */
public class SegmentarCerebro extends javax.swing.JFrame {

    public AxpherPicture ventanaPrincipal;
    /**
     * Creates new form SegmentarCerebro
     */
    public SegmentarCerebro(AxpherPicture ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        setLocationRelativeTo(ventanaPrincipal);
        new ControladorSegmentacion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelCanvasKmeans = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelCanvasSegmentacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboKmeans = new javax.swing.JComboBox();
        btnVisualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMateriaBlanca = new javax.swing.JButton();
        btnMateriaGris = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Segmentacion de Cerebro");
        setPreferredSize(new java.awt.Dimension(1024, 512));
        setResizable(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(234, 77, 116));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "K-Means", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel5.setPreferredSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout panelCanvasKmeansLayout = new javax.swing.GroupLayout(panelCanvasKmeans);
        panelCanvasKmeans.setLayout(panelCanvasKmeansLayout);
        panelCanvasKmeansLayout.setHorizontalGroup(
            panelCanvasKmeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        panelCanvasKmeansLayout.setVerticalGroup(
            panelCanvasKmeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCanvasKmeans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCanvasKmeans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(104, 184, 84));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segmentacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout panelCanvasSegmentacionLayout = new javax.swing.GroupLayout(panelCanvasSegmentacion);
        panelCanvasSegmentacion.setLayout(panelCanvasSegmentacionLayout);
        panelCanvasSegmentacionLayout.setHorizontalGroup(
            panelCanvasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        panelCanvasSegmentacionLayout.setVerticalGroup(
            panelCanvasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCanvasSegmentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCanvasSegmentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(237, 206, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 40));

        jLabel1.setText("Seleccionar K-Means");
        jPanel1.add(jLabel1);

        comboKmeans.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboKmeans);

        btnVisualizar.setText("Visualizar");
        jPanel1.add(btnVisualizar);

        jLabel2.setText("Segmentar");
        jPanel1.add(jLabel2);

        btnMateriaBlanca.setText("Materia Blanca");
        jPanel1.add(btnMateriaBlanca);

        btnMateriaGris.setText("Materia Gris");
        jPanel1.add(btnMateriaGris);

        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegmentarCerebro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegmentarCerebro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegmentarCerebro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegmentarCerebro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new SegmentarCerebro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnMateriaBlanca;
    public javax.swing.JButton btnMateriaGris;
    public javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox comboKmeans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelCanvasKmeans;
    private javax.swing.JPanel panelCanvasSegmentacion;
    // End of variables declaration//GEN-END:variables
}
